name: build-ssm-env-action

author: Heronlabs

description: Build SSM env

inputs:
  AWS_REGION:
    description: inputs.AWS_REGION
    required: true
  AWS_ACCESS_KEY_ID:
    description: inputs.AWS_ACCESS_KEY_ID
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: inputs.AWS_SECRET_ACCESS_KEY
    required: true
  AWS_ENV_PATH:
    description: inputs.AWS_ENV_PATH
    required: true

runs:
  using: composite
  steps:
    - name: '[BUILD] | Create env file'
      shell: bash
      run: |
        chmod +x ./build-ssm-env-action/core/ssm-to-env.sh
        ./build-ssm-env-action/core/ssm-to-env.sh
      env:
        AWS_REGION: ${{ inputs.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_ENV_PATH: ${{ inputs.AWS_ENV_PATH }}
