name: build-ssm-env-action

author: Heron Labs

description: Build SSM env

inputs:
  AWS_ROLE_TO_ASSUME:
    description: inputs.AWS_ROLE_TO_ASSUME
    required: true
  AWS_REGION:
    description: inputs.AWS_REGION
    required: true
  AWS_ROLE_DURATION_SECONDS:
    description: inputs.AWS_ROLE_DURATION_SECONDS
    required: true
  AWS_ENV_PATH:
    description: inputs.AWS_ENV_PATH
    required: true

runs:
  using: composite
  steps:
    - name: '[BUILD] | Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: ${{ inputs.AWS_ROLE_DURATION_SECONDS }}
        role-session-name: build-ssm-env-action-session

    - name: '[BUILD] | Create env file'
      shell: bash
      run: |
        chmod +x ./build-ssm-env-action/core/ssm-to-env.sh
        ./build-ssm-env-action/core/ssm-to-env.sh
      env:
        AWS_ENV_PATH: ${{ inputs.AWS_ENV_PATH }}
