name: '[ CD ] | Continuous Delivery'

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      spec:
        description: The SEMVER specification.
        required: true
        type: choice
        default: patch
        options:
          - 'major'
          - 'minor'
          - 'patch'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: heronlabs/action-tag-release-build@7b9529804115cb5c5023c7f3ad2a7a218c618d44 # v4.0.1
        with:
          github-token: ${{ github.token }}
          spec: ${{ inputs.spec }}
